version: "3.8"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sqli_lab
      MYSQL_USER: lab
      MYSQL_PASSWORD: labpassword
    volumes:
      - ./db/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: ./flask-app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=sqli_lab
      - DB_USER=lab
      - DB_PASS=labpassword
      - FLASK_SECRET=supersecretdev
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app

volumes:
  mysql_data:
